server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:auth_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  application:
    name: auth-service
    
jwt:
  secret: 9d3b6a7c8f1e2d3c4b5a6f7e8c9d0a1b9d3b6a7c8f1e2d3c
  expiration: 3600000
